# Generated by Django 3.0.7 on 2020-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0005_auto_20200701_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='packages',
            name='tags',
            field=models.ManyToManyField(to='Travelapp.Tag'),
        ),
    ]
